version: '3.9'

services:
  keybridge-db:
    image: postgres:16
    container_name: keybridge-db
    env_file: ".env"
    ports:
      - ${KEYBRIDGE_DB_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${KEYBRIDGE_DB_PASSWORD}
      - POSTGRES_USER =${KEYBRIDGE_DB_USERNAME}
      - KEYBRIDGE_DB=${KEYBRIDGE_DB_NAME}
    restart: always

  keybridge-api:
    build:
      context: .
    image: keybridge-api:latest
    container_name: keybridge-api
    env_file: ".env"
    ports:
      - ${KEYBRIDGE_API_PORT}:5000
    environment:
      - KEYBRIDGE_DB_USERNAME=${KEYBRIDGE_DB_USERNAME}
      - KEYBRIDGE_DB_PASSWORD=${KEYBRIDGE_DB_PASSWORD}
      - KEYBRIDGE_DB_HOST=keybridge-db
      - KEYBRIDGE_DB_PORT=${KEYBRIDGE_DB_PORT}
      - KEYBRIDGE_DB_NAME=${KEYBRIDGE_DB_NAME}
      - KEYBRIDGE_API_PORT=${KEYBRIDGE_API_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - keybridge-db
    restart: always
